### ISSUE TITLE
update acme_tiny.py (using ACME v2 since March 2018)

### ISSUE THREAD

**Issue by matrey** [matrey/acme-tiny-auto#4]
https://github.com/diafygi/acme-tiny
> NOTE: Since Let's Encrypt's ACME v2 release (acme-tiny 4.0.0+), the intermediate certificate is included in the issued certificate download, so you no longer have to independently download the intermediate certificate and concatenate it to your signed certificate. If you have an bash script using acme-tiny <4.0 (e.g. before 2018-03-17) with acme-tiny 4.0.0+, then you may be adding the intermediate certificate to your signed_chain.crt twice

**Comment by matrey** [comment]
Even more needed now, as the agreement URL changed

```
Traceback (most recent call last):
  File "/acme/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/acme/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/acme/acme_tiny.py", line 92, in get_crt
    raise ValueError("Error registering: {0} {1}".format(code, result))
ValueError: Error registering: 400 {
  "type": "urn:acme:error:malformed",
  "detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf]",
  "status": 400
}
```

**Comment by matrey** [comment]
Now using acme_tiny v4.0.4 (5350420d35177eda733d85096433a24e55f8d00e) from May 18th 2018
